version: '3.8'

networks:
  npcine_net:
    driver: bridge

services:
  # ========================================
  # 1. DATABASES & CACHE & MESSAGE BROKER
  # ========================================
  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: npcine_db
    ports:
      - "5432:5432"
    networks:
      - npcine_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d npcine_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq_broker:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_broker
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - npcine_net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis_cache:
    image: redis:alpine
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - npcine_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ========================================
  # 2. MICROSERVICES
  # ========================================
  user-service:
    build: ./user-service
    image: ${DOCKER_USERNAME}/npcine-user-service:latest
    container_name: user-service
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - npcine_net
    depends_on:
      rabbitmq_broker:
        condition: service_healthy
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq_broker
<<<<<<< HEAD
      - MONGO_URI=${MONGO_URI}/user_db
=======
      - SPRING_MONGODB_URI= MONGO_CLUSTER_BASE_URI_HERE
      - SECURITY_ADMIN_EMAILS=${SECURITY_ADMIN_EMAILS:-admin@npcine.com}
>>>>>>> 5bd9b4d5d8f517f25c7210ac78ca247c88c6b051

  movies-service:
    build: ./movies-service
    image: ${DOCKER_USERNAME}/npcine-movies-service:latest
    container_name: movies-service
    restart: unless-stopped
    networks:
      - npcine_net
    depends_on:
      rabbitmq_broker:
        condition: service_healthy
    environment:
<<<<<<< HEAD
      - MONGO_URI=${MONGO_URI}/movie_db
=======
      - SPRING_DATA_MONGODB_URI= MONGO_CLUSTER_BASE_URI_HERE
>>>>>>> 5bd9b4d5d8f517f25c7210ac78ca247c88c6b051

  booking-service:
    build: ./booking-service
    image: ${DOCKER_USERNAME}/npcine-booking-service:latest
    container_name: booking-service
    restart: unless-stopped
    ports:
      - "8082:8082"
    networks:
      - npcine_net
    depends_on:
      postgres_db:
        condition: service_healthy
      rabbitmq_broker:
        condition: service_healthy
      redis_cache:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/npcine_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_RABBITMQ_HOST=rabbitmq_broker
      - SPRING_DATA_REDIS_HOST=redis_cache
      - SPRING_DATA_REDIS_PORT=6379

  payment-service:
    build: ./payment-service
    image: ${DOCKER_USERNAME}/npcine-payment-service:latest
    container_name: payment-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    networks:
      - npcine_net
    depends_on:
      postgres_db:
        condition: service_healthy
      rabbitmq_broker:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/npcine_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_RABBITMQ_HOST=rabbitmq_broker

  notification-service:
    build: ./notification_service
    image: ${DOCKER_USERNAME}/npcine-notification-service:latest
    container_name: notification-service
    restart: unless-stopped
    ports:
      - "8084:8084"
    networks:
      - npcine_net
    depends_on:
      rabbitmq_broker:
        condition: service_healthy
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq_broker

  # ========================================
  # 3. API GATEWAY
  # ========================================
  api-gateway:
    build: ./api-gateway
    image: ${DOCKER_USERNAME}/npcine-api-gateway:latest
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - npcine_net
    depends_on:
      - user-service
      - movies-service
      - booking-service
      - payment-service
      - notification-service
