spring.application.name=booking-service
server.port=8082

# Shared JWT config (must match user-service and api-gateway)
jwt.secret=${JWT_SECRET:1JwCQ6Ipyd1CxytJccCkB754iRXoRlEly0HujDiqgkRZ4ZlmIUasTMwFhgl9kYep}
jwt.expiration=${JWT_EXPIRATION:3600000}
