spring.application.name=user-service

# MongoDB Cloud Connection (No Tabs, No Spaces)
spring.mongodb.uri=${SPRING_MONGODB_URI:mongodb+srv://rahul23256:HkPpPssSIpJPdgUY@cluster0.qe3y3wr.mongodb.net/user_db?appName=Cluster0}
spring.data.mongodb.auto-index-creation=true
management.health.mongo.enabled=false

# Mail Settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vermarahul11034@gmail.com
spring.mail.password=jwcy saxt kxgy ivws
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Server & Actuator
server.port=8080
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Security JWT
jwt.secret=1JwCQ6Ipyd1CxytJccCkB754iRXoRlEly0HujDiqgkRZ4ZlmIUasTMwFhgl9kYep
jwt.expiration=3600000
security.admin.emails=${SECURITY_ADMIN_EMAILS:admin@npcine.com}